// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen, within } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { ThemeProvider } from '../../features/theme/ThemeProvider';
import { SideScroller } from './SideScroller';
import { createSideScroller, type SceneStatus, type SideScrollerScene } from './scene';
import { toggleColor } from './model';

vi.mock('./scene', () => ({ createSideScroller: vi.fn() }));
vi.mock('./TutorialDemo', () => ({ TutorialDemo: () => <div>玩法動畫示範</div> }));
afterEach(() => { cleanup(); vi.resetAllMocks(); });
const fakeScene = (): SideScrollerScene => ({ hold: vi.fn(), tap: vi.fn(), setMode: vi.fn(), toggleColor: vi.fn(), pressControl: vi.fn(), setTutorial: vi.fn(), destroy: vi.fn() });
it('開始入口只在巡覽中央，功能列只接受點擊且焦點回遊戲，沒有暫停或重啟操作', async () => {
  const created = fakeScene();
  vi.mocked(createSideScroller).mockImplementation(async (_host, _signal, onStatus) => {
    created.setMode = vi.fn(mode => onStatus({ mode, paused: false, completed: false, checkpoint: 0, falls: 0, lap: 1, color: null, collectedGems: [] }));
    return created;
  });
  render(<ThemeProvider><SideScroller /></ThemeProvider>);
  await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  expect(screen.getByRole('link', { name: '← 回冒險座' }).getAttribute('href')).toBe('/pages/activities.html#games');
  expect(screen.getByRole('button', { name: '世界巡覽' }).getAttribute('aria-pressed')).toBe('true');
  expect(screen.getByRole('button', { name: '跳躍' }).hasAttribute('disabled')).toBe(true);
  expect(screen.queryByRole('button', { name: '向左移動' })).toBeNull();
  const actions = screen.getByRole('group', { name: '場景功能' });
  expect(within(actions).queryByRole('button', { name: '開始冒險' })).toBeNull();
  expect(within(actions).queryByRole('link', { name: '回冒險座' })).toBeNull();
  [...within(actions).getAllByRole('button'), ...within(screen.getByRole('group', { name: '關卡難度' })).getAllByRole('button')].forEach(button => expect(button.tabIndex).toBe(-1));
  expect(screen.getByRole('button', { name: '開始冒險' }).closest('.ss-playfield')).toBeTruthy();
  fireEvent.click(screen.getByRole('button', { name: '開始冒險' })); expect(created.setMode).toHaveBeenCalledWith('play');
  expect(screen.queryByRole('button', { name: '開始冒險' })).toBeNull();
  const jump = screen.getByRole('button', { name: '跳躍' });
  fireEvent.keyDown(jump, { key: 'Enter' }); fireEvent.keyUp(jump, { key: 'Enter' });
  expect(created.hold).toHaveBeenNthCalledWith(1, 'jump', true, 'button-jump');
  expect(created.hold).toHaveBeenNthCalledWith(2, 'jump', false, 'button-jump');
  for (const name of ['暫停', '繼續', '從頭開始']) expect(screen.queryByRole('button', { name })).toBeNull();
  const stage = screen.getByRole('region', { name: '橫向遊戲世界' });
  expect(stage.contains(screen.getByRole('group', { name: '場景功能' }))).toBe(true);
  expect(stage.contains(screen.getByRole('group', { name: '關卡難度' }))).toBe(true);
  expect(created.setMode).toHaveBeenCalledTimes(1);
  expect(document.activeElement).toBe(screen.getByRole('region', { name: '橫向遊戲世界' }));
  fireEvent.click(screen.getByRole('button', { name: '世界巡覽' })); expect(created.setMode).toHaveBeenLastCalledWith('preview');
  expect(screen.getByRole('button', { name: '開始冒險' })).toBeTruthy();
  expect(screen.getByRole('button', { name: '跳躍' }).hasAttribute('disabled')).toBe(true);
  cleanup(); expect(created.destroy).toHaveBeenCalledOnce();
});
it('兩按鈕可同時開啟紫色並獨立關閉；重看手冊只凍結場景、不重啟冒險', async () => {
  const created = fakeScene();
  vi.mocked(createSideScroller).mockImplementation(async (_host, _signal, onStatus) => {
    let status: SceneStatus = { mode: 'preview', paused: false, completed: false, checkpoint: 0, falls: 0, lap: 1, color: null, collectedGems: [] };
    created.toggleColor = vi.fn(button => { status = { ...status, color: toggleColor(status.color, button) }; onStatus(status); });
    created.setMode = vi.fn(mode => { status = { ...status, mode, paused: false }; onStatus(status); });
    return created;
  });
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  const red = screen.getByRole('button', { name: '紅燈' }), blue = screen.getByRole('button', { name: '藍燈' });
  expect(red.getAttribute('aria-pressed')).toBe('false'); expect(blue.getAttribute('aria-pressed')).toBe('false');
  act(() => {
    fireEvent(red, new MouseEvent('pointerdown', { button: 0, bubbles: true, cancelable: true }));
    fireEvent(blue, new MouseEvent('pointerdown', { button: 0, bubbles: true, cancelable: true }));
  });
  expect(created.toggleColor).toHaveBeenCalledTimes(2);
  expect(red.getAttribute('aria-pressed')).toBe('true'); expect(blue.getAttribute('aria-pressed')).toBe('true');
  expect(screen.getByRole('status').textContent).toContain('紅＋藍開啟 · 紫色地板實體');
  fireEvent.click(blue, { detail: 1 }); expect(created.toggleColor).toHaveBeenCalledTimes(2);
  expect(document.activeElement).toBe(screen.getByRole('region', { name: '橫向遊戲世界' }));
  fireEvent.click(red); expect(red.getAttribute('aria-pressed')).toBe('false'); expect(blue.getAttribute('aria-pressed')).toBe('true');
  fireEvent.click(blue); expect(blue.getAttribute('aria-pressed')).toBe('false');
  fireEvent.click(screen.getByRole('button', { name: '開始冒險' })); fireEvent.click(screen.getByRole('button', { name: '玩法手冊' }));
  expect(red.hasAttribute('disabled')).toBe(true); expect(blue.hasAttribute('disabled')).toBe(true); expect(screen.getByRole('button', { name: '跳躍' }).hasAttribute('disabled')).toBe(true);
  fireEvent.click(screen.getByRole('button', { name: '返回遊戲' }));
  expect(created.setMode).toHaveBeenCalledTimes(1);
  expect(red.hasAttribute('disabled')).toBe(false); expect(blue.hasAttribute('disabled')).toBe(false);
});
it('離場會取消載入；延遲完成的舊場景必須銷毀', async () => {
  let resolve!: (scene: SideScrollerScene) => void;
  vi.mocked(createSideScroller).mockImplementation(() => new Promise(done => { resolve = done; }));
  const view = render(<ThemeProvider><SideScroller /></ThemeProvider>);
  const signal = vi.mocked(createSideScroller).mock.calls[0][1];
  view.unmount(); expect(signal.aborted).toBe(true);
  const created = fakeScene();
  await act(async () => resolve(created));
  expect(created.destroy).toHaveBeenCalledOnce(); expect(created.setMode).not.toHaveBeenCalled();
});
it('開場四頁手冊阻止跑道前進，可依序看完障礙教學，開始後可重看並返回', async () => {
  const created = fakeScene(); vi.mocked(createSideScroller).mockResolvedValue(created);
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  const manual = screen.getByRole('dialog');
  expect(created.setTutorial).toHaveBeenLastCalledWith(true);
  expect(screen.getByRole('heading', { name: '歡迎來到魔法禁書庫' })).toBeTruthy();
  fireEvent.keyDown(manual, { key: 'ArrowRight' });
  expect(screen.getByRole('heading', { name: '點亮，才站得穩' })).toBeTruthy();
  fireEvent.keyDown(manual, { key: 'ArrowRight' });
  expect(screen.getByRole('heading', { name: '兩盞燈，一起亮' })).toBeTruthy();
  fireEvent.keyDown(manual, { key: 'ArrowRight' });
  expect(screen.getByRole('heading', { name: '淡化方塊，選擇岔路' })).toBeTruthy();
  expect(screen.getByText('旅人手冊 · 4 / 4')).toBeTruthy();
  const buttons = screen.getAllByRole('button', { name: '開始冒險' }); fireEvent.click(buttons.at(-1)!);
  expect(screen.queryByRole('dialog')).toBeNull(); expect(created.setTutorial).toHaveBeenLastCalledWith(false);
  expect(created.setMode).toHaveBeenCalledWith('play');
  fireEvent.click(screen.getByRole('button', { name: '玩法手冊' }));
  expect(created.setTutorial).toHaveBeenLastCalledWith(true);
  fireEvent.click(screen.getByRole('button', { name: '返回遊戲' }));
  expect(created.setTutorial).toHaveBeenLastCalledWith(false); expect(created.setMode).toHaveBeenCalledTimes(1);
  expect(screen.getByRole('button', { name: '跳躍' }).textContent).toBe('跳躍');
  expect(screen.getByRole('button', { name: '紅燈' }).textContent).toBe('紅燈');
  expect(screen.getByRole('button', { name: '藍燈' }).textContent).toBe('藍燈');
});
it('預設零星，選三星重建場景；過期的零星載入不可覆蓋三星', async () => {
  let resolveIntro!: (scene: SideScrollerScene) => void;
  const intro = fakeScene(), challenge = fakeScene();
  vi.mocked(createSideScroller).mockImplementation((_host, _signal, _onStatus, level) => level?.difficulty === 0 ? new Promise(done => { resolveIntro = done; }) : Promise.resolve(challenge));
  render(<ThemeProvider><SideScroller /></ThemeProvider>);
  const firstSignal = vi.mocked(createSideScroller).mock.calls[0][1];
  expect(vi.mocked(createSideScroller).mock.calls[0][3]?.difficulty).toBe(0);
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: /3 星關卡/ })); });
  expect(firstSignal.aborted).toBe(true);
  expect(screen.getByRole('button', { name: /3 星關卡/ }).getAttribute('aria-pressed')).toBe('true');
  expect(vi.mocked(createSideScroller).mock.calls.at(-1)?.[3]?.difficulty).toBe(3);
  await act(async () => resolveIntro(intro));
  expect(intro.destroy).toHaveBeenCalledOnce(); expect(challenge.destroy).not.toHaveBeenCalled();
  expect(challenge.setTutorial).toHaveBeenLastCalledWith(false);
});
it.each(['preview', 'play'] as const)('關閉手冊至 %s 時先置中並交還焦點，再放行跑道', async mode => {
  const created = fakeScene(), order: string[] = [];
  vi.mocked(createSideScroller).mockResolvedValue(created);
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  const stage = screen.getByRole('region', { name: '橫向遊戲世界' });
  stage.scrollIntoView = vi.fn(() => order.push('center'));
  created.setMode = vi.fn(() => { expect(document.activeElement).toBe(stage); order.push('start'); });
  created.setTutorial = vi.fn(open => { if (!open) { expect(document.activeElement).toBe(stage); order.push('release'); } });
  if (mode === 'play') fireEvent.click(screen.getByRole('button', { name: '前往第 4 頁' }));
  fireEvent.click(screen.getByRole('button', { name: mode === 'preview' ? '先看世界' : '開始冒險' }));
  expect(stage.scrollIntoView).toHaveBeenCalledWith({ behavior: 'instant', block: 'center', inline: 'nearest' });
  expect(order).toEqual(mode === 'play' ? ['center', 'start', 'release'] : ['center', 'release']);
  expect(document.activeElement).toBe(stage);
});
it('巡覽開始前先置中，跌落重生不顯示開始入口；切換難度仍自動巡覽並交還焦點', async () => {
  const created = fakeScene(); let emit!: (status: SceneStatus) => void;
  vi.mocked(createSideScroller).mockImplementation(async (_host, _signal, onStatus) => { emit = onStatus; return created; });
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  const stage = screen.getByRole('region', { name: '橫向遊戲世界' });
  stage.scrollIntoView = vi.fn();
  created.setMode = vi.fn(mode => {
    expect(stage.scrollIntoView).toHaveBeenCalledOnce(); expect(document.activeElement).toBe(stage);
    emit({ mode, paused: false, completed: false, checkpoint: 0, falls: 0, lap: 1, color: null, collectedGems: [] });
  });
  fireEvent.click(screen.getByRole('button', { name: '開始冒險' }));
  act(() => emit({ mode: 'play', paused: false, completed: false, checkpoint: 2, falls: 1, lap: 1, color: null, collectedGems: [] }));
  expect(screen.queryByRole('button', { name: '開始冒險' })).toBeNull();
  expect(created.setMode).toHaveBeenCalledOnce();
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: /5 星關卡/ })); });
  expect(screen.getByRole('button', { name: '開始冒險' })).toBeTruthy();
  expect(document.activeElement).toBe(stage);
  expect(screen.getByRole('button', { name: '世界巡覽' }).getAttribute('aria-pressed')).toBe('true');
});
it('可選一星平台跑道，原高難度保留三星', async () => {
  const created = fakeScene(); vi.mocked(createSideScroller).mockResolvedValue(created);
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  expect(screen.getByRole('button', { name: /4 星關卡/ })).toBeTruthy();
  expect(screen.getByRole('button', { name: /3 星關卡/ })).toBeTruthy();
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: /1 星關卡/ })); });
  expect(vi.mocked(createSideScroller).mock.calls.at(-1)?.[3]?.difficulty).toBe(1);
  expect(screen.getByRole('button', { name: /1 星關卡/ }).getAttribute('aria-pressed')).toBe('true');
  expect(created.destroy).toHaveBeenCalledOnce();
});
it('提供0至4星五個關卡，可選二星雙光迴廊', async () => {
  const created = fakeScene(); vi.mocked(createSideScroller).mockResolvedValue(created);
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  for (const stars of [0, 1, 2, 3, 4]) expect(screen.getByRole('button', { name: new RegExp(`${stars} 星關卡`) })).toBeTruthy();
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: /2 星關卡/ })); });
  expect(vi.mocked(createSideScroller).mock.calls.at(-1)?.[3]?.difficulty).toBe(2);
  expect(screen.getByRole('button', { name: /2 星關卡/ }).getAttribute('aria-pressed')).toBe('true');
});
it.each([[4, '晶石岔路'], [5, '晶光試煉']] as const)('選 %i 星 %s 直接巡覽，不強制重看手冊；手動開啟仍有四頁', async (difficulty, name) => {
  const created = fakeScene(); vi.mocked(createSideScroller).mockResolvedValue(created);
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: `${difficulty} 星關卡：${name}` })); });
  expect(vi.mocked(createSideScroller).mock.calls.at(-1)?.[3]?.difficulty).toBe(difficulty);
  expect(created.setTutorial).toHaveBeenLastCalledWith(false);
  expect(screen.queryByRole('dialog')).toBeNull();
  fireEvent.click(screen.getByRole('button', { name: '玩法手冊' }));
  expect(screen.getByRole('heading', { name: '歡迎來到魔法禁書庫' })).toBeTruthy();
  fireEvent.click(screen.getByRole('button', { name: '前往第 4 頁' }));
  expect(screen.getByRole('heading', { name: '淡化方塊，選擇岔路' })).toBeTruthy();
  expect(screen.getByText(/點亮同色燈就能穿過/)).toBeTruthy();
  expect(screen.getByText(/沒點對顏色，撞上就會掉落/)).toBeTruthy();
  expect(screen.getByText(/兩條路都通往出口/)).toBeTruthy();
  fireEvent.click(screen.getAllByRole('button', { name: '開始冒險' }).at(-1)!);
  expect(created.setTutorial).toHaveBeenLastCalledWith(false); expect(created.setMode).toHaveBeenLastCalledWith('play');
  expect(screen.queryByRole('dialog')).toBeNull();
});
it('四種寶石收藏同步收集狀態，切關清空；手冊每頁皆不介紹彩蛋', async () => {
  let emit!: (status: SceneStatus) => void;
  vi.mocked(createSideScroller).mockImplementation(async (_host, _signal, onStatus) => { emit = onStatus; return fakeScene(); });
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  for (let page = 0; page < 4; page++) {
    expect(screen.getByRole('dialog').textContent).not.toMatch(/寶石|收集|蒐集/);
    expect(document.querySelector('#ss-manual-body')!.textContent!.length).toBeLessThan(70);
    expect(document.querySelector('.ss-manual-hint')!.textContent!.length).toBeLessThan(70);
    if (page < 3) fireEvent.click(screen.getByRole('button', { name: '下一頁' }));
  }
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  const gems = screen.getByRole('group', { name: '寶石收藏' });
  expect(within(gems).getAllByRole('img')).toHaveLength(4);
  expect(within(gems).getByRole('img', { name: '黃寶石：未收集' })).toBeTruthy();
  act(() => emit({ mode: 'play', paused: false, completed: false, checkpoint: 1, falls: 1, lap: 1, color: null, collectedGems: ['yellow', 'red'] }));
  expect(within(gems).getByRole('img', { name: '黃寶石：已收集' })).toBeTruthy();
  expect(within(gems).getByRole('img', { name: '紅寶石：已收集' })).toBeTruthy();
  expect(within(gems).getByRole('img', { name: '綠寶石：未收集' })).toBeTruthy();
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: /5 星關卡/ })); });
  expect(within(gems).getAllByRole('img', { name: /未收集/ })).toHaveLength(4);
});
it('六個關卡選項只顯示難度與名稱，畫面及輔助科技名稱都不包含秒數', async () => {
  vi.mocked(createSideScroller).mockResolvedValue(fakeScene());
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  const menu = screen.getByRole('group', { name: '關卡難度' });
  const buttons = within(menu).getAllByRole('button');
  expect(buttons).toHaveLength(6);
  expect(menu.textContent).not.toMatch(/秒|約/);
  buttons.forEach((button, index) => {
    expect(button.getAttribute('aria-label')).toMatch(new RegExp(`^${index} 星關卡：`));
    expect(button.getAttribute('aria-label')).not.toContain('秒');
  });
  expect(within(menu).getByRole('button', { name: '5 星關卡：晶光試煉' })).toBeTruthy();
});
it('三個觸控區依序為跳躍、紅燈、藍燈；多指切燈不會放開跳躍，取消接觸會釋放各自按壓', async () => {
  const created = fakeScene();
  vi.mocked(createSideScroller).mockImplementation(async (_host, _signal, onStatus) => {
    created.setMode = vi.fn(mode => onStatus({ mode, paused: false, completed: false, checkpoint: 0, falls: 0, lap: 1, color: null, collectedGems: [] }));
    return created;
  });
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  fireEvent.click(screen.getByRole('button', { name: '開始冒險' }));
  const jump = screen.getByRole('button', { name: '跳躍' }), red = screen.getByRole('button', { name: '紅燈' }), blue = screen.getByRole('button', { name: '藍燈' });
  expect([...jump.parentElement!.querySelectorAll('button')].map(button => button.dataset.control)).toEqual(['jump', 'red', 'blue']);
  const pointer = (button: HTMLElement, type: string, pointerId: number) => {
    const event = new MouseEvent(type, { button: 0, bubbles: true, cancelable: true });
    Object.defineProperty(event, 'pointerId', { value: pointerId }); fireEvent(button, event);
  };
  pointer(jump, 'pointerdown', 11); pointer(red, 'pointerdown', 12); pointer(blue, 'pointerdown', 13);
  expect(created.hold).toHaveBeenCalledWith('jump', true, 'pointer-11');
  expect(created.hold).not.toHaveBeenCalledWith('jump', false, 'pointer-11');
  expect(created.toggleColor).toHaveBeenNthCalledWith(1, 'red'); expect(created.toggleColor).toHaveBeenNthCalledWith(2, 'blue');
  expect(created.pressControl).toHaveBeenCalledWith('red', true, 'pointer-12');
  expect(created.pressControl).toHaveBeenCalledWith('blue', true, 'pointer-13');
  pointer(red, 'pointercancel', 12); pointer(blue, 'lostpointercapture', 13); pointer(jump, 'pointerup', 11);
  expect(created.pressControl).toHaveBeenCalledWith('red', false, 'pointer-12');
  expect(created.pressControl).toHaveBeenCalledWith('blue', false, 'pointer-13');
  expect(created.hold).toHaveBeenCalledWith('jump', false, 'pointer-11');
  fireEvent.click(red, { detail: 1 }); expect(created.toggleColor).toHaveBeenCalledTimes(2);
});
