// @vitest-environment jsdom
import { act, cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { ThemeProvider } from '../../features/theme/ThemeProvider';
import { SideScroller } from './SideScroller';
import { createSideScroller, type SceneStatus, type SideScrollerScene } from './scene';
import { toggleColor } from './model';

vi.mock('./scene', () => ({ createSideScroller: vi.fn() }));
vi.mock('./TutorialDemo', () => ({ TutorialDemo: () => <div>玩法動畫示範</div> }));
afterEach(() => { cleanup(); vi.resetAllMocks(); });
const fakeScene = (): SideScrollerScene => ({ hold: vi.fn(), tap: vi.fn(), setMode: vi.fn(), toggleColor: vi.fn(), togglePause: vi.fn(), setTutorial: vi.fn(), restart: vi.fn(), destroy: vi.fn() });
it('提供回冒險座入口、可用鍵盤的控制與重試操作', async () => {
  const created = fakeScene();
  vi.mocked(createSideScroller).mockImplementation(async (_host, _signal, onStatus) => {
    created.setMode = vi.fn(mode => onStatus({ mode, paused: false, completed: false, checkpoint: 0, falls: 0, lap: 1, color: null }));
    return created;
  });
  render(<ThemeProvider><SideScroller /></ThemeProvider>);
  await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  expect(screen.getByRole('link', { name: '← 回冒險座' }).getAttribute('href')).toBe('/pages/activities.html#games');
  expect(screen.getByRole('button', { name: '世界巡覽' }).getAttribute('aria-pressed')).toBe('true');
  expect(screen.queryByRole('button', { name: '跳躍' })).toBeNull();
  expect(screen.queryByRole('button', { name: '向左移動' })).toBeNull();
  fireEvent.click(screen.getByRole('button', { name: '開始冒險' })); expect(created.setMode).toHaveBeenCalledWith('play');
  const jump = screen.getByRole('button', { name: '跳躍' });
  fireEvent.keyDown(jump, { key: 'Enter' }); fireEvent.keyUp(jump, { key: 'Enter' });
  expect(created.hold).toHaveBeenNthCalledWith(1, 'jump', true, 'button-jump');
  expect(created.hold).toHaveBeenNthCalledWith(2, 'jump', false, 'button-jump');
  fireEvent.click(screen.getByRole('button', { name: '從頭開始' })); expect(created.restart).toHaveBeenCalledOnce();
  expect(document.activeElement).toBe(screen.getByRole('region', { name: '橫向遊戲世界' }));
  fireEvent.click(screen.getByRole('button', { name: '世界巡覽' })); expect(created.setMode).toHaveBeenLastCalledWith('preview');
  expect(screen.queryByRole('button', { name: '跳躍' })).toBeNull();
  cleanup(); expect(created.destroy).toHaveBeenCalledOnce();
});
it('兩按鈕可同時開啟紫色，保持獨立開關；暫停巡覽仍可檢視顏色', async () => {
  const created = fakeScene();
  vi.mocked(createSideScroller).mockImplementation(async (_host, _signal, onStatus) => {
    let status: SceneStatus = { mode: 'preview', paused: false, completed: false, checkpoint: 0, falls: 0, lap: 1, color: null };
    created.toggleColor = vi.fn(button => { status = { ...status, color: toggleColor(status.color, button) }; onStatus(status); });
    created.togglePause = vi.fn(() => { status = { ...status, paused: !status.paused }; onStatus(status); });
    created.setMode = vi.fn(mode => { status = { ...status, mode, paused: false }; onStatus(status); });
    created.restart = vi.fn(() => { status = { ...status, color: null, paused: false }; onStatus(status); });
    return created;
  });
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  const red = screen.getByRole('button', { name: '紅燈' }), blue = screen.getByRole('button', { name: '藍燈' });
  expect(red.getAttribute('aria-pressed')).toBe('false'); expect(blue.getAttribute('aria-pressed')).toBe('false');
  act(() => {
    fireEvent(red, new MouseEvent('pointerdown', { button: 0, bubbles: true, cancelable: true }));
    fireEvent(blue, new MouseEvent('pointerdown', { button: 0, bubbles: true, cancelable: true }));
  });
  expect(created.toggleColor).toHaveBeenCalledTimes(2);
  expect(red.getAttribute('aria-pressed')).toBe('true'); expect(blue.getAttribute('aria-pressed')).toBe('true');
  expect(screen.getByRole('status').textContent).toContain('紅＋藍開啟 · 紫色實體');
  fireEvent.click(blue, { detail: 1 }); expect(created.toggleColor).toHaveBeenCalledTimes(2);
  expect(document.activeElement).toBe(screen.getByRole('region', { name: '橫向遊戲世界' }));
  fireEvent.click(screen.getByRole('button', { name: '暫停' })); expect(blue.hasAttribute('disabled')).toBe(false);
  fireEvent.click(red); expect(red.getAttribute('aria-pressed')).toBe('false'); expect(blue.getAttribute('aria-pressed')).toBe('true');
  fireEvent.click(blue); expect(blue.getAttribute('aria-pressed')).toBe('false');
  fireEvent.click(screen.getByRole('button', { name: '開始冒險' })); fireEvent.click(screen.getByRole('button', { name: '暫停' }));
  expect(red.hasAttribute('disabled')).toBe(true); expect(blue.hasAttribute('disabled')).toBe(true); expect(screen.getByRole('button', { name: '跳躍' }).hasAttribute('disabled')).toBe(true);
  fireEvent.click(screen.getByRole('button', { name: '從頭開始' })); expect(red.getAttribute('aria-pressed')).toBe('false'); expect(blue.getAttribute('aria-pressed')).toBe('false');
});
it('離場會取消載入；延遲完成的舊場景必須銷毀', async () => {
  let resolve!: (scene: SideScrollerScene) => void;
  vi.mocked(createSideScroller).mockImplementation(() => new Promise(done => { resolve = done; }));
  const view = render(<ThemeProvider><SideScroller /></ThemeProvider>);
  const signal = vi.mocked(createSideScroller).mock.calls[0][1];
  view.unmount(); expect(signal.aborted).toBe(true);
  const created = fakeScene();
  await act(async () => resolve(created));
  expect(created.destroy).toHaveBeenCalledOnce(); expect(created.restart).not.toHaveBeenCalled();
});
it('開場三頁手冊阻止跑道前進，可用鍵盤翻頁，開始後可重看並返回', async () => {
  const created = fakeScene(); vi.mocked(createSideScroller).mockResolvedValue(created);
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  const manual = screen.getByRole('dialog');
  expect(created.setTutorial).toHaveBeenLastCalledWith(true);
  expect(screen.getByRole('heading', { name: '歡迎來到魔法禁書庫' })).toBeTruthy();
  fireEvent.keyDown(manual, { key: 'ArrowRight' });
  expect(screen.getByRole('heading', { name: '點亮，才站得穩' })).toBeTruthy();
  fireEvent.keyDown(manual, { key: 'ArrowRight' });
  expect(screen.getByRole('heading', { name: '兩盞燈，一起亮' })).toBeTruthy();
  const buttons = screen.getAllByRole('button', { name: '開始冒險' }); fireEvent.click(buttons.at(-1)!);
  expect(screen.queryByRole('dialog')).toBeNull(); expect(created.setTutorial).toHaveBeenLastCalledWith(false);
  expect(created.setMode).toHaveBeenCalledWith('play');
  fireEvent.click(screen.getByRole('button', { name: '玩法手冊' }));
  expect(created.setTutorial).toHaveBeenLastCalledWith(true);
  fireEvent.click(screen.getByRole('button', { name: '返回遊戲' }));
  expect(created.setTutorial).toHaveBeenLastCalledWith(false); expect(created.setMode).toHaveBeenCalledTimes(1);
  expect(screen.getByRole('button', { name: '紅燈' }).textContent).toBe('紅燈 1');
  expect(screen.getByRole('button', { name: '藍燈' }).textContent).toBe('藍燈 2');
});
it('預設零星，選三星重建場景；過期的零星載入不可覆蓋三星', async () => {
  let resolveIntro!: (scene: SideScrollerScene) => void;
  const intro = fakeScene(), challenge = fakeScene();
  vi.mocked(createSideScroller).mockImplementation((_host, _signal, _onStatus, level) => level?.difficulty === 0 ? new Promise(done => { resolveIntro = done; }) : Promise.resolve(challenge));
  render(<ThemeProvider><SideScroller /></ThemeProvider>);
  const firstSignal = vi.mocked(createSideScroller).mock.calls[0][1];
  expect(vi.mocked(createSideScroller).mock.calls[0][3]?.difficulty).toBe(0);
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: /3 星關卡/ })); });
  expect(firstSignal.aborted).toBe(true);
  expect(screen.getByRole('button', { name: /3 星關卡/ }).getAttribute('aria-pressed')).toBe('true');
  expect(vi.mocked(createSideScroller).mock.calls.at(-1)?.[3]?.difficulty).toBe(3);
  await act(async () => resolveIntro(intro));
  expect(intro.destroy).toHaveBeenCalledOnce(); expect(challenge.destroy).not.toHaveBeenCalled();
  expect(challenge.setTutorial).toHaveBeenLastCalledWith(false);
});
it('可選一星平台跑道，原高難度顯示三星且不再顯示四星', async () => {
  const created = fakeScene(); vi.mocked(createSideScroller).mockResolvedValue(created);
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  expect(screen.queryByRole('button', { name: /4 星關卡/ })).toBeNull();
  expect(screen.getByRole('button', { name: /3 星關卡/ })).toBeTruthy();
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: /1 星關卡/ })); });
  expect(vi.mocked(createSideScroller).mock.calls.at(-1)?.[3]?.difficulty).toBe(1);
  expect(screen.getByRole('button', { name: /1 星關卡/ }).getAttribute('aria-pressed')).toBe('true');
  expect(created.destroy).toHaveBeenCalledOnce();
});
it('提供0至3星四個關卡，可選二星雙光迴廊', async () => {
  const created = fakeScene(); vi.mocked(createSideScroller).mockResolvedValue(created);
  render(<ThemeProvider><SideScroller /></ThemeProvider>); await act(async () => {});
  fireEvent.click(screen.getByRole('button', { name: '先看世界' }));
  for (const stars of [0, 1, 2, 3]) expect(screen.getByRole('button', { name: new RegExp(`${stars} 星關卡`) })).toBeTruthy();
  await act(async () => { fireEvent.click(screen.getByRole('button', { name: /2 星關卡/ })); });
  expect(vi.mocked(createSideScroller).mock.calls.at(-1)?.[3]?.difficulty).toBe(2);
  expect(screen.getByRole('button', { name: /2 星關卡/ }).getAttribute('aria-pressed')).toBe('true');
});
