from PIL import Image
from pathlib import Path
import json
project=Path(__file__).resolve().parent.parent
from workshop_art_paths import source, DISPLAY
sheet=Image.open(source('rustic-workshop-v2.png')).convert('RGBA'); print('sheet',sheet.size)
cell=sheet.width//2
specs={}
for name,index,size in [('spring-rustic',0,384),('recycler-rustic',1,320),('book-novice',2,128),('exit-fullscreen',None,96)]:
 im=Image.open(source('exit-fullscreen-v2.png')).convert('RGBA') if index is None else sheet.crop((index%2*cell,index//2*cell,(index%2+1)*cell,(index//2+1)*cell))
 print(name,'source',im.size,im.getchannel('A').point(lambda v:255 if v>=8 else 0).getbbox())
 if name in ('spring-rustic','recycler-rustic'):
  im=Image.open(source('spring-stone-v4.png' if name=='spring-rustic' else 'recycler-muted-v4.png')).convert('RGBA')
 out=Image.new('RGBA',(size,size));inner=round(size*.78);off=(size-inner)//2
 out.alpha_composite(im.resize((inner,inner),Image.Resampling.LANCZOS),(off,off))
 filename={'spring-rustic':'spring-stone-v4.webp','recycler-rustic':'recycler-muted-v4.webp'}.get(name,name+'-v2.webp')
 path=DISPLAY/filename;out.save(path,quality=88,method=6)
 bbox=out.getchannel('A').point(lambda v:255 if v>=8 else 0).getbbox()
 specs[name]={'file':path.name,'bounds':[round(v/size,5) for v in bbox],'size':size}
 print(name,bbox,path.stat().st_size)
(project/'src/games/magic-workshop/rustic-art.ts').write_text('/** Generated by scripts/prepare-workshop-rustic.py. */\nexport const RUSTIC_ART = '+json.dumps(specs,indent=2)+' as const;\n',encoding='utf-8')
