/** Generated by scripts/prepare-workshop-rustic.py. */
export const RUSTIC_ART = {
  "spring-rustic": {
    "file": "spring-stone-v4.webp",
    "bounds": [
      0.14323,
      0.3125,
      0.86719,
      0.73177
    ],
    "size": 384
  },
  "recycler-rustic": {
    "file": "recycler-muted-v4.webp",
    "bounds": [
      0.175,
      0.29688,
      0.825,
      0.74375
    ],
    "size": 320
  },
  "book-novice": {
    "file": "book-novice-v2.webp",
    "bounds": [
      0.23438,
      0.16406,
      0.83594,
      0.80469
    ],
    "size": 128
  },
  "exit-fullscreen": {
    "file": "exit-fullscreen-v2.webp",
    "bounds": [
      0.29167,
      0.30208,
      0.69792,
      0.6875
    ],
    "size": 96
  }
} as const;
